(specifications->manifest
 '("bash"
   "coreutils"
   "diffutils"
   "emacs-magit"
   "emacs-package-lint"
   "emacs-transient"
   "emacs-yaml"
   "emacs"
   "findutils"
   "git"
   "make"
   "ripgrep"))
